micronaut:
  application:
    name: madrasatyApi

#datasources:
#  default:
#    url: jdbc:postgresql://localhost:5432/postgres
#    driverClassName: org.postgresql.Driver
#    username: postgres
#    password: 'sa'
#    schema-generate: CREATE_DROP
#    dialect: POSTGRES

jpa:
  default:
    reactive: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        connection:
          url: jdbc:postgresql://localhost:5432/madrasaty
          username: madrasaty
          password: 1234
          dialect: POSTGRES
netty:
  default:
    allocator:
      max-order: 3
